server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# AWS Account Credentials (AWS 접근 키)
cloud:
  aws:
    credentials:
      accessKey: AKIASXSSFL6PEGXXX27F    # AWS IAM AccessKey 적기
      secretKey: bYB9cDfhttvDTeXA8kbqyNb39n2ZdETBl3npbXtz  # AWS IAM SecretKey 적기
    # AWS S3 bucket Info (S3 버킷정보)
    s3:
      bucket: main055
    region:
      static: ap-northeast-2
    stack:
      auto: false



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pre055.cixzxikdlatt.ap-northeast-2.rds.amazonaws.com:3306/main055?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: psy411301
  jpa:
    hibernate:
      ddl-auto: validate  # (1) ??? ?? ??
    show-sql: true # (2) SQL ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # file upload max size (파일 업로드 크기 설정)
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


